In [ ]:
import pickle as pkl

In [ ]:
with open("asd.pkl", "rb") as f:
    data = pkl.load(f)

In [ ]:
data.keys()

In [1]:
import logging
import sys

# Get the root logger
root_logger = logging.getLogger()
root_logger.setLevel(logging.INFO)

# Remove existing handlers (avoid duplicates in Jupyter)
if root_logger.hasHandlers():
    root_logger.handlers.clear()

# Add a stream handler to show logs in notebook/stdout
stream_handler = logging.StreamHandler(sys.stdout)
stream_handler.setLevel(logging.INFO)
formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(name)s - %(message)s", "%H:%M:%S")
stream_handler.setFormatter(formatter)

root_logger.addHandler(stream_handler)

print("✅ Logger configured for notebook output")

✅ Logger configured for notebook output

In [1]:
import pandas as pd

from forcateri import TimeSeries


if __name__ == "__main__":
    steps, deltas = 3, 2
    dti = pd.date_range(start="2000-01-01", freq="D", periods=steps)
    tdi = pd.timedelta_range(start=0, freq="D", periods=deltas)
    mi = pd.MultiIndex.from_product([tdi, dti])

    df = pd.DataFrame(
        data=range(steps * deltas),
        index=mi,
        columns=pd.MultiIndex.from_product(
            [["some_feature"], ["value"]], names=TimeSeries.COL_INDEX_NAMES
        ),
    )
    ts = TimeSeries(df)

In [ ]:
row_index_names = TimeSeries.ROW_INDEX_NAMES
row_index_names

In [2]:
ts.data

feature           some_feature
representation           value
offset time_stamp
0 days 2000-01-01            0
       2000-01-02            1
       2000-01-03            2
1 days 2000-01-01            3
       2000-01-02            4
       2000-01-03            5

In [ ]:
#q_hca_q0.1, q_hca_q0.5

feature           some_feature
representation           value
0 days 2000-01-01            0
       2000-01-02            1
       2000-01-03            2
1 days 2000-01-01            3
       2000-01-02            4
       2000-01-03            5